apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-helm-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: helm-website
  template:
    metadata:
      labels:
        app.kubernetes.io/name: helm-website
    spec:
      containers:
        - name: helm-website
          image: "ghcr.io/alexander-moser/website:main"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
